#!/usr/bin/env bash
# Renders the jira-cli-snapshot cask from a GoReleaser snapshot dist/.
# GoReleaser OSS only writes casks on real releases, so the snapshot channel
# renders the same shape itself, with checksums from the snapshot build.
#
# Usage: render-snapshot-cask.sh <dist-dir> <release-tag>
# The cask is written to stdout.
set -euo pipefail

DIST="$1"
TAG="$2"

VERSION=$(jq -r .version "$DIST/metadata.json")

sha() {
  awk -v f="jira_${VERSION}_$1.tar.gz" '$2 == f { print $1 }' "$DIST/checksums.txt" | grep .
}

MACOS_INTEL=$(sha macOS_x86_64)
MACOS_ARM=$(sha macOS_arm64)
LINUX_INTEL=$(sha linux_x86_64)
LINUX_ARM=$(sha linux_arm64)

cat <<EOF
# This file was generated by the snapshot workflow in rethab/jira-cli. DO NOT EDIT.
cask "jira-cli-snapshot" do
  version "$VERSION"

  on_macos do
    on_intel do
      sha256 "$MACOS_INTEL"
      url "https://github.com/rethab/jira-cli/releases/download/$TAG/jira_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_macOS_x86_64/bin/jira", "bin/jira"
    end
    on_arm do
      sha256 "$MACOS_ARM"
      url "https://github.com/rethab/jira-cli/releases/download/$TAG/jira_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_macOS_arm64/bin/jira", "bin/jira"
    end
  end

  on_linux do
    on_intel do
      sha256 "$LINUX_INTEL"
      url "https://github.com/rethab/jira-cli/releases/download/$TAG/jira_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_linux_x86_64/bin/jira", "bin/jira"
    end
    on_arm do
      sha256 "$LINUX_ARM"
      url "https://github.com/rethab/jira-cli/releases/download/$TAG/jira_#{version}_linux_arm64.tar.gz",
        verified: "github.com/rethab/jira-cli/"
      rename "jira_#{version}_linux_arm64/bin/jira", "bin/jira"
    end
  end

  name "jira-cli-snapshot"
  desc "🔥 Feature-rich interactive Jira command-line (snapshot of main)"
  homepage "https://github.com/rethab/jira-cli"

  livecheck do
    skip "Auto-generated on every merge to main."
  end

  conflicts_with cask: "jira-cli"

  binary "bin/jira"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/jira"]
    end
  end
  generate_completions_from_executable "bin/jira", "completion",
    shells: [:bash, :zsh, :fish]

  caveats "This is an unstable snapshot build of the main branch."
end
EOF
