run:
  timeout: 5m
  deadline: 5m
  skip-dirs-use-default: true
linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - godot
    - gofumpt
    - gomnd
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - prealloc
    - unparam
    - varcheck
  fast: false
linters-settings:
  gofmt:
    simplify: false
  testpackage:
    skip-regexp: ".*"
  gocyclo:
    min-complexity: 15
issues:
  exclude-use-default: false
