run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - godot
    - gofumpt
    - gomnd
    - gosimple
    - govet
    - ineffassign
    - prealloc
    - unparam
    - unused
  fast: false
linters-settings:
  gofmt:
    simplify: false
  testpackage:
    skip-regexp: ".*"
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: package-comments
        disabled: true
  gomnd:
    ignored-numbers: ['0', '1', '2', '3']
issues:
  exclude-use-default: false
  exclude-dirs-use-default: true
