project_name: jira

release:
  prerelease: auto
  name_template: "v{{.Version}}"

before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      binary: bin/jira
      main: ./cmd/jira
      ldflags:
        - -s -w
        - -X github.com/ankitpokhrel/jira-cli/internal/version.Version={{.Version}}
        - -X github.com/ankitpokhrel/jira-cli/internal/version.GitCommit={{.Commit}}
        - -X github.com/ankitpokhrel/jira-cli/internal/version.BuildDate={{time "2006-01-02"}}"
      env:
        - CGO_ENABLED=0
    id: macOS
    goos: [darwin]
    goarch: [amd64, arm64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64]

archives:
  - id: nix
    builds: [macOS, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    replacements:
      darwin: macOS
      386: i386
      amd64: x86_64
    format: tar.gz
    files:
      - LICENSE

  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

brews:
  - name: jira-cli
    homepage: "https://github.com/ankitpokhrel/jira-cli"
    description: "🔥 Feature-rich interactive Jira command-line"
    license: "MIT"

    ids:
      - nix

    # GOARM to specify which 32-bit arm version to use if there are multiple versions
    # from the build section. Brew formulas support only one 32-bit version atm.
    goarm: 6

    tap:
      owner: ankitpokhrel
      name: homebrew-jira-cli

    test: |
      system "#{bin}/jira --help"
      assert_includes help_text, "Usage:"

    install: |
      system "make install" if build.head?
      bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"

    custom_block: |
      head do
        url "https://github.com/ankitpokhrel/jira-cli.git", branch: "main"
        depends_on "go"
      end

    commit_author:
      name: ankitpokhrel
      email: hello@ankit.pl

    commit_msg_template: "Formula update for version {{ .Tag }}"

    # Folder inside the repository to put the formula to.
    folder: Formula

    # This will prevent goreleaser to actually try to commit the updated
    # formula - leaving the responsibility of publishing it to the user.
    skip_upload: true

changelog:
  skip: true
  sort: desc
  filters:
    exclude:
      - '^doc:'
      - '^dev:'
      - '^build:'
      - '^ci:'
